"""
dashboard/pages/2_MonteCarlo.py
P10/P50/P90 risk band via residual-bootstrapped Monte Carlo, with
gauge instruments, a fan chart, and any-percentile lookup.
"""

import streamlit as st
import pandas as pd
import numpy as np
import json
import os
import sys
import plotly.graph_objects as go

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
from dashboard.theme import apply_theme, page_header, kpi_strip, gauge_chart, TEXT, TEXT_DIM, AMBER, STEEL, GREEN, RED, YELLOW, PANEL_ALT, BORDER
from src.monte_carlo.monte_carlo_simulation import run_monte_carlo
from scipy.stats import gaussian_kde

st.set_page_config(page_title="Monte Carlo Risk | Drilling AI", page_icon="🎲", layout="wide")
apply_theme()
page_header("RISK INSTRUMENTATION", "🎲 Monte Carlo Risk Analysis",
            "P10/P50/P90 generated by sampling 10,000 times from the trained model's real residual errors — "
            "centered on a feature-aware ML prediction, not a generic assumed curve.")

MODELS_DIR = "models"
TARGETS = ["Duration_Hours", "Total_Cost_USD", "NPT_Hours"]
LABELS = {"Duration_Hours": "Duration (hrs)", "Total_Cost_USD": "Cost (USD)", "NPT_Hours": "NPT (hrs)"}
FMT = {"Duration_Hours": "{:.2f}", "Total_Cost_USD": "${:,.0f}", "NPT_Hours": "{:.2f}"}
UNIT = {"Duration_Hours": "hrs", "Total_Cost_USD": "$", "NPT_Hours": "hrs"}

if "last_prediction" not in st.session_state:
    st.warning("No forecast in this session yet. Visit **Forecasting** first, or enter values manually below.")

manual = st.checkbox("Enter point predictions manually", value=("last_prediction" not in st.session_state))

predictions = {}
if manual:
    c1, c2, c3 = st.columns(3)
    predictions["Duration_Hours"] = c1.number_input("Predicted Duration (hrs)", value=12.0, min_value=0.0)
    predictions["Total_Cost_USD"] = c2.number_input("Predicted Cost (USD)", value=62000.0, min_value=0.0)
    predictions["NPT_Hours"] = c3.number_input("Predicted NPT (hrs)", value=1.9, min_value=0.0)
else:
    predictions = st.session_state["last_prediction"]

results = {}
for target in TARGETS:
    meta = json.load(open(os.path.join(MODELS_DIR, f"{target}_metadata.json")))
    residuals = meta["residuals"]
    results[target] = run_monte_carlo(predictions[target], residuals, n_sim=10000)

st.write("")

# ---- Gauge row: instrument-style P10/P50/P90 dials ----
st.markdown("##### 🎛️ Risk Gauges — Live Reading")
g1, g2, g3 = st.columns(3)
for col, target in zip([g1, g2, g3], TARGETS):
    res = results[target]
    fig = gauge_chart(res["point_prediction"], res["P10"], res["P50"], res["P90"], LABELS[target], unit=UNIT[target] if UNIT[target] != "$" else "")
    col.plotly_chart(fig, width='stretch')

st.write("")

# ---- KPI strip with P10/P50/P90 ----
for target in TARGETS:
    res = results[target]
    fmt = FMT[target]
    spread_pct = res["spread"] / res["P50"] * 100 if res["P50"] != 0 else 0
    st.markdown(f"###### {LABELS[target]}")
    kpi_strip([
        {"label": "P10 · Optimistic", "value": fmt.format(res["P10"]), "level": "Low"},
        {"label": "P50 · Most Likely", "value": fmt.format(res["P50"])},
        {"label": "P90 · Conservative", "value": fmt.format(res["P90"]), "level": "High"},
        {"label": "Spread (P90−P10)", "value": fmt.format(res["spread"]), "sub": f"{spread_pct:.0f}% of P50"},
    ])
    st.write("")

st.divider()

# ---- Smooth Probability Density Curve (the classic risk "bell curve") ----
st.markdown("##### 📈 Probability Density Curve")
st.caption("This is the actual shape of the risk distribution — smoothed from 10,000 Monte Carlo simulations into a continuous probability curve, the way risk engineers present P10/P50/P90 in industry reports.")
target_to_plot = st.selectbox("Select metric to visualize", TARGETS, format_func=lambda x: LABELS[x])
res = results[target_to_plot]
sim = res["simulated"]
fmt = FMT[target_to_plot]

# Fit a smooth density curve (Gaussian KDE) over the simulated outcomes
kde = gaussian_kde(sim)
x_min, x_max = sim.min(), sim.max()
x_grid = np.linspace(x_min, x_max, 400)
y_density = kde(x_grid)

fig = go.Figure()

# Shade: below P10 (green = optimistic / unlikely-low risk zone)
mask_low = x_grid <= res["P10"]
fig.add_trace(go.Scatter(
    x=x_grid[mask_low], y=y_density[mask_low], fill="tozeroy", mode="lines",
    line=dict(width=0), fillcolor="rgba(61,220,151,0.25)", name="< P10", showlegend=False,
))
# Shade: P10 to P90 (amber = the "likely" 80% confidence zone)
mask_mid = (x_grid >= res["P10"]) & (x_grid <= res["P90"])
fig.add_trace(go.Scatter(
    x=x_grid[mask_mid], y=y_density[mask_mid], fill="tozeroy", mode="lines",
    line=dict(width=0), fillcolor="rgba(232,163,61,0.30)", name="P10-P90 (80% likely)", showlegend=False,
))
# Shade: above P90 (red = conservative / unlikely-high risk zone)
mask_high = x_grid >= res["P90"]
fig.add_trace(go.Scatter(
    x=x_grid[mask_high], y=y_density[mask_high], fill="tozeroy", mode="lines",
    line=dict(width=0), fillcolor="rgba(232,84,61,0.25)", name="> P90", showlegend=False,
))
# The smooth curve outline itself
fig.add_trace(go.Scatter(
    x=x_grid, y=y_density, mode="lines", line=dict(color=AMBER, width=2.5),
    name="Probability density", showlegend=False,
))

# Percentile marker lines with annotations
for p, name, color in [(res["P10"], "P10", GREEN), (res["P50"], "P50", AMBER), (res["P90"], "P90", RED)]:
    y_at_p = float(kde(p)[0])
    fig.add_trace(go.Scatter(
        x=[p, p], y=[0, y_at_p], mode="lines",
        line=dict(color=color, width=2, dash="dash"), showlegend=False,
    ))
    fig.add_annotation(x=p, y=y_at_p, text=f"<b>{name}</b><br>{fmt.format(p)}",
                        showarrow=True, arrowhead=2, arrowcolor=color, font=dict(color=color, size=11),
                        ay=-40)

fig.update_layout(
    height=440,
    title=f"Risk Distribution Curve — {LABELS[target_to_plot]} (smoothed from 10,000 simulations)",
    xaxis_title=LABELS[target_to_plot], yaxis_title="Probability Density",
    showlegend=False, hovermode="x",
)
st.plotly_chart(fig, width='stretch')

c1, c2, c3 = st.columns(3)
c1.markdown(f'<div class="rig-card" style="text-align:center;"><span style="color:{GREEN};">●</span> Below P10 — <b>10%</b> chance outcome lands here</div>', unsafe_allow_html=True)
c2.markdown(f'<div class="rig-card" style="text-align:center;"><span style="color:{AMBER};">●</span> P10–P90 — <b>80%</b> confidence zone (the planning range)</div>', unsafe_allow_html=True)
c3.markdown(f'<div class="rig-card" style="text-align:center;"><span style="color:{RED};">●</span> Above P90 — <b>10%</b> chance outcome lands here</div>', unsafe_allow_html=True)

st.divider()
st.markdown("##### 📊 Simulation Histogram (raw 10,000 samples, for cross-check)")
with st.expander("Show raw histogram", expanded=False):
    counts, bins = np.histogram(sim, bins=70)
    bin_centers = (bins[:-1] + bins[1:]) / 2
    colors = [GREEN if b < res["P10"] else RED if b > res["P90"] else AMBER for b in bin_centers]
    fig_hist = go.Figure(go.Bar(x=bin_centers, y=counts, marker=dict(color=colors, opacity=0.85),
                                  width=(bins[1]-bins[0])*0.95))
    fig_hist.update_layout(height=320, showlegend=False, bargap=0.02,
                            xaxis_title=LABELS[target_to_plot], yaxis_title="Frequency (out of 10,000)")
    st.plotly_chart(fig_hist, width='stretch')

st.divider()

# ---- Custom percentile lookup ----
st.markdown("##### 🔍 Custom Percentile Lookup — Any Value, Any Decimal")
st.caption("P10/P50/P90 are just defaults. Pull any percentile you need for your planning policy — P9.1, P55.7, P91.5, anything.")
c1, c2, c3 = st.columns(3)
custom_p1 = c1.number_input("Percentile #1", min_value=0.0, max_value=100.0, value=10.0, step=0.1, format="%.1f")
custom_p2 = c2.number_input("Percentile #2", min_value=0.0, max_value=100.0, value=50.0, step=0.1, format="%.1f")
custom_p3 = c3.number_input("Percentile #3", min_value=0.0, max_value=100.0, value=90.0, step=0.1, format="%.1f")
vals = np.percentile(sim, [custom_p1, custom_p2, custom_p3])
kpi_strip([
    {"label": f"P{custom_p1:g}", "value": fmt.format(vals[0])},
    {"label": f"P{custom_p2:g}", "value": fmt.format(vals[1])},
    {"label": f"P{custom_p3:g}", "value": fmt.format(vals[2])},
])

st.session_state["mc_results"] = results
